const ErrorCodes = {
    ROUTING_ERROR: 1,
    INVALID_TYPE: 2,
    DATABASE_ERROR: 3,
    DESLOGUEO_ERROR: 4,
    AUTENTICACION_ERROR: 5,
    ADMIN_NOAUTHORIZATION: 6,
    PRODUCT_ERROR: 7,
    CART_ERROR: 8,
    USER_ERROR: 9,
    TICKET_ERROR: 10,
    FILE_ERROR: 11,
}

export default ErrorCodes;